import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme/themeProvider"
import Nav from "@/components/nav/nav"
import Head from "next/head"
import Image from "../assets/ogimage.webp"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "WordWiz",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Head>
        <title>WordWiz</title>
        <meta
          name="description"
          content="WordWiz is your ultimate tool for wordsmiths, generated by create next app"
        />
        <meta
          name="keywords"
          content="WordWiz, textutil, anish , create next app, SEO, Next.js"
        />
        <link rel="canonical" href="https://wordwiz.vercel.app" />

        {/* Open Graph Tags */}
        <meta property="og:title" content="WordWiz" />
        <meta
          property="og:description"
          content="WordWiz is your ultimate tool for wordsmiths, generated by create next app"
        />
        <meta
          property="og:image"
          content="https://wordwiz.vercel.app/../assets/ogimage.webp"
        />
        <meta property="og:url" content="https://wordwiz.vercel.app" />
        <meta property="og:type" content="website" />

        {/* Twitter Card Tags */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="WordWiz" />
        <meta
          name="twitter:description"
          content="WordWiz is your ultimate tool for wordsmiths, generated by create next app"
        />
        <meta
          name="twitter:image"
          content="https://wordwiz.vercel.app/../assets/ogimage.webp"
        />
      </Head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Nav />
          <div className="light:bg-black">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  )
}
